#!/bin/bash

now="$(date +'%Y%m%d')"

case $1 in
  "init")
    echo "echo 'post-commit started' && pelican `pwd`/www/content -o `pwd`/www/output -s `pwd`/www/pelicanconf.py && ghp-import `pwd`/www/output && git push origin gh-pages" > .git/hooks/post-commit
    chmod +x .git/hooks/post-commit
  ;;
  "content")
    cd ./www
    pelican content
  ;;
  "publish")
    counter=0
    for link in `cat ./links`; do
      echo "Title: Image $counter" > ./www/content/$counter.md
      echo "Date: $now" >> ./www/content/$counter.md
      echo "Category: Instagram" >> ./www/content/$counter.md
      echo "Very very beautiful image :)" >> ./www/content/$counter.md
      echo "![image][$link]" >> ./www/content/$counter.md
      let counter++
    done
    rm ./links
  ;;
  "install")
    pip install ghp-import pelican markdown requests
  ;;
  *)
    echo "WTF !"
  ;;
esac
